---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/alpine-build

run:
  path: src/build.sh
    
inputs:
  - name: src
  - name: libressl
  - name: lua-build
  - name: libslz-build

outputs:
  - name: out
  
